### ISSUE TITLE
Upload EuroVocBERT to the Hugging Face model library

### ISSUE THREAD

**Issue by CeriseGoutPelican** [racai-ai/pyeurovoc#4]
Good afternoon,

First of all, I would like to thank everyone who has contributed to pyeurovoc. The work done is amazing.

I was wondering if you would consider uploading EuroVocBERT to the Hugging Face models library to share with more people? It could then be used through the Inference API or simply loaded through the a transformer's pipeline.

**Comment by avramandrei** [comment]
Hi, 

Firstly, sorry for the late reply, it has been a crazy week.

Secondly, thank you for your kind words and feedback! Yes, we are considering uploading the models in the HuggingFace library. However, I can't give an exact period/date when this would happen.

**Comment by CeriseGoutPelican** [comment]
Thank you very much for your comment and for considering uploading the model!
